<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.bsc.langgraph4j</groupId>
		<artifactId>langgraph4j-ag-ui-parent</artifactId>
		<version>1.9-SNAPSHOT</version>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<artifactId>langgraph4j-ag-ui-sdk</artifactId>
	<name>langgraph4j::ag-ui::sdk</name>
	<description>Langgraph4j integrate AG-UI protocol using AG-UI Community SDK</description>
	<url>https://github.com/langgraph4j/langgraph4j-copilotkit</url>
	<licenses>
		<license>
			<name>MIT</name>
		</license>
	</licenses>
	<developers>
		<developer>
			<name>bsorrentino</name>
			<email>bartolomeo.sorrentino@gmail.com</email>
		</developer>
	</developers>

	<properties>
		<spring-ai.version>2.0.0</spring-ai.version>
	</properties>

	<dependencyManagement>
		<dependencies>

			<dependency>
				<groupId>org.springframework.ai</groupId>
				<artifactId>spring-ai-bom</artifactId>
				<version>${spring-ai.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

			<dependency>
				<groupId>org.springframework</groupId>
				<artifactId>spring-framework-bom</artifactId>
				<version>7.0.8</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter-parent</artifactId>
				<version>4.1.0</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>

		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<version>1.5.37</version>
			<scope>provided</scope>
		</dependency>
<!--
		<dependency>
			<groupId>com.ag-ui.community</groupId>
			<artifactId>java-client</artifactId>
			<version>${ag-ui.version}</version>
		</dependency>

		<dependency>
			<groupId>com.ag-ui.community</groupId>
			<artifactId>java-json</artifactId>
			<version>${ag-ui.version}</version>
		</dependency>
-->
		<dependency>
			<groupId>com.ag-ui.community</groupId>
			<artifactId>java-server</artifactId>
			<version>${ag-ui.version}</version>
		</dependency>

		<dependency>
			<groupId>org.bsc.langgraph4j</groupId>
			<artifactId>langgraph4j-core</artifactId>
		</dependency>

		<dependency>
			<groupId>org.bsc.langgraph4j</groupId>
			<artifactId>langgraph4j-ag-ui-json</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
		</dependency>

		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-core</artifactId>
			<scope>provided</scope>
		</dependency>


		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context</artifactId>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-webmvc</artifactId>
			<scope>provided</scope>
		</dependency>

		<!--
		================================================
		TEST
		================================================
		-->
		<dependency>
			<groupId>org.bsc.langgraph4j</groupId>
			<artifactId>langgraph4j-javelit</artifactId>
			<scope>test</scope>
			<optional>true</optional>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<scope>test</scope>
		</dependency>
		<!--
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
			<scope>test</scope>
		</dependency>
		-->

		<dependency>
			<groupId>org.springframework.ai</groupId>
			<artifactId>spring-ai-commons</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.springframework.ai</groupId>
			<artifactId>spring-ai-model</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.springframework.ai</groupId>
			<artifactId>spring-ai-client-chat</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.springframework.ai</groupId>
			<artifactId>spring-ai-ollama</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.springframework.ai</groupId>
			<artifactId>spring-ai-openai</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.bsc.langgraph4j</groupId>
			<artifactId>langgraph4j-spring-ai</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.bsc.langgraph4j</groupId>
			<artifactId>langgraph4j-springai-agentexecutor</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>com.ag-ui.community</groupId>
			<artifactId>java-ok-http</artifactId>
			<version>4.12.0</version>
			<scope>test</scope>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>3.6.0</version>
				<executions>
					<execution>
						<id>ag-ui-fatjar</id>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<shadedArtifactAttached>true</shadedArtifactAttached>
							<shadedClassifierName>all</shadedClassifierName>
							<createDependencyReducedPom>false</createDependencyReducedPom>
							<artifactSet>
								<includes>
									<include>com.ag-ui.community:*</include>
								</includes>
							</artifactSet>
						</configuration>
					</execution>
				</executions>
			</plugin>


		</plugins>
	</build>

	<profiles>
<!--
		<profile>
			<id>macos-dns-native</id>
			<activation>
				<os>
					<family>mac</family>
					<arch>aarch64</arch>
				</os>
			</activation>
			<dependencies>
				<dependency>
					<groupId>io.netty</groupId>
					<artifactId>netty-resolver-dns-native-macos</artifactId>
					<version>4.1.115.Final</version>
					<classifier>osx-aarch_64</classifier>
					<scope>runtime</scope>
				</dependency>
			</dependencies>
		</profile>
-->
	</profiles>

</project>
